<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginSuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>31d87fd3-aeca-44bc-aed8-e2360b9c1d48</testSuiteGuid>
   <testCaseLink>
      <guid>a95501a6-9dc0-4d56-8d92-0b38e6415c40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase1/DataFromExcel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ab7861f-d5f9-4a86-82da-10b279501efe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7ab7861f-d5f9-4a86-82da-10b279501efe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>88e3d16e-5237-4493-832d-f4626da14161</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ab7861f-d5f9-4a86-82da-10b279501efe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2df69cdd-de4a-4e0a-b070-9df8996aca33</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
